#!/usr/bin/env python
"""
This file wil be the main executable to start the backup of the
current system.
This executable will create all that is needed for the restore
"""

# vim: tabstop=4 expandtab shiftwidth=4 softtabstop=4

import dpkg

if __name__ == '__main__':
    dpkg = dpkg.Dpkg()
    dpkg_list = dpkg.make_dpkg_listing()
    config_files = list()
    for pkg in dpkg_list:
        config_files.extend(dpkg.find_altered_config(pkg))
    print config_files
