#!/usr/bin/env python
"""
This file wil be the main executable to start the backup of the
current system.
This executable will create all that is needed for the restore
"""

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
import dpkg

if __name__ == '__main__':
    dpkg = dpkg.Dpkg()
    dpkg_list = dpkg.make_dpkg_listing()
    print dpkg_list
